language: java
notifications:
  slack:
    secure: zEpFwp7e5t0dnvd/BX7gFctTB7ZrZ8gFDPMy/fEAP2jaVr2QZ9QMOBaCiHCqeROUQBD6yGG44KmQ9y7YXVIRD2gVBSk8wPVBWyZy7R3ZJZSXzQc/jCWHysOXAc+7Iik5U/8ZBZDN6Nk07g6hrr0Y1b4xhB9j4mQ3g1pL1DzjQycVP1YMUbauslZkPd1vWGBaLVeehge1XeTgoxQrQKFD+MGzaWzUYQbrmXYV5kLslqC4dOotxuUZFPlZOcgg8+l5/RNNCcTnE/AHTn7L0YeZSILdS+0AI3iAzmyyjrGWB5jux+pE4mxpfLSiG4NMYp/nRjsfKSzEHDZq9C0n4yRzgwDYLRBT4jDpPVKLRg/i4pPXKOpUcTUYsh3jwiNZOmg+htkYTMVR7ryVn/b2KMUu8IRz5NtBYwZKLajfcS8SLYscwvxp1OrwGIFScUN0wGqN+My+zqDwtKZ3xNZRU8yzulo0u/HUykm1K91laiobSFA08KjFBcarBr700z8QDdtRloLokxVVZgc8nWD1aKSoLlMbQIhN0IvXgFiN42eloYM/AvSkr3llsFff+7OiZUE2aWEY26RQj6pBC2pij+6oDceKsB1rXaSBueUG7rqJW9DR1Sw5yNtDjbALYtq6LPg47JWxDVfsg/FrySswGtWmLVQ4azqftktd4rU4RSFd7m0=
deploy:
  provider: releases
  api_key:
    secure: xXQTnU1tZvK4pzD936ggd61FP7m8Gpq7393wv8gQ5qzyGUvQCRrkUFC/0fUAOnNvZm0h2HZ4y7tvJIqiGqPx8q+p3sZR3cZ5OOUTiL5BxMntj0BowS7DhpFmcRDggQy7/frvzRoFFiRks2fFUiAh9reANcHNeWlPvDkvpNZyajOpnpvvwd7PWevCYKA1e5yg3Bv3qup2xW4601qfw9SXtIRW92Yi71Hy3aWlo/F+aluACS5vIwCJueRV749UDfhPUgduzleqKdWQ6ePD/eNFLtBCjIQP2r/4tshim0HiRuy63AUcNg7lZZX+gSIbYQLvKI99n5Pg29yfiMrgRcHeSgczuKE/Y8MaxY04mgVgKf5+imJn5WG2KhL56hjFlBujQcvtMziJ+bXEyqahIhQ5HN9ZZm26XSZin/s72xHPb/+ZX93VPWcbcXVOgXbp6CRrrk0YILRHgg9HnOhJQYggbGwGUvN4beOuQ5THfqouOksmui7kiBLh1XFXYPJwOWMXafoJ8fCUQM2Hh9BGViIXi274HMrZM81uurUuXnHtvLGHXa9cwed/AfAJuwkndhNfkLqMAK+eEs0EUD8f47+ZmE9UwhH9XI3vuvNAwX5nMp5GLULpRrDGv6X+7CIdOc2T8TF7eX28np39Ph9bK/59mY4GZLKxr0nasNUJ203d5ZU=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-backup-dictionaries-plugin
