language: java
notifications:
  slack:
    secure: zEpFwp7e5t0dnvd/BX7gFctTB7ZrZ8gFDPMy/fEAP2jaVr2QZ9QMOBaCiHCqeROUQBD6yGG44KmQ9y7YXVIRD2gVBSk8wPVBWyZy7R3ZJZSXzQc/jCWHysOXAc+7Iik5U/8ZBZDN6Nk07g6hrr0Y1b4xhB9j4mQ3g1pL1DzjQycVP1YMUbauslZkPd1vWGBaLVeehge1XeTgoxQrQKFD+MGzaWzUYQbrmXYV5kLslqC4dOotxuUZFPlZOcgg8+l5/RNNCcTnE/AHTn7L0YeZSILdS+0AI3iAzmyyjrGWB5jux+pE4mxpfLSiG4NMYp/nRjsfKSzEHDZq9C0n4yRzgwDYLRBT4jDpPVKLRg/i4pPXKOpUcTUYsh3jwiNZOmg+htkYTMVR7ryVn/b2KMUu8IRz5NtBYwZKLajfcS8SLYscwvxp1OrwGIFScUN0wGqN+My+zqDwtKZ3xNZRU8yzulo0u/HUykm1K91laiobSFA08KjFBcarBr700z8QDdtRloLokxVVZgc8nWD1aKSoLlMbQIhN0IvXgFiN42eloYM/AvSkr3llsFff+7OiZUE2aWEY26RQj6pBC2pij+6oDceKsB1rXaSBueUG7rqJW9DR1Sw5yNtDjbALYtq6LPg47JWxDVfsg/FrySswGtWmLVQ4azqftktd4rU4RSFd7m0=
deploy:
  provider: releases
  api_key:
    secure: KaGB8xEOuS7LIfJnhOD3xbMu0Yxis3aCYzkQOHeigqYCMGazYJ3f3mcOH7kqKHXh6mzxC1GvdTL1e6pkH56FBB3GI3nBJTAJFe6U07OOv2zcHau1D9CJ0VlWsHjwaUm9t6cBSyHbFg0kJL485G75hk3TwpUiIrFpADeuPVubuZIz3ooJZhbiUvYdYEohQWEfWwW/S2nzNd5mrh6RmujZe7DMWzMnL11zE/BbI9RG8cjGco0zjQnfnq8b6j/4zq/2Dsj/dlW34yDnxZIwdv3eTXq08/TsuQzfcIyUw1sn9/ucy3077+v2EsBfq3utqSRFp9K+EZ2Zx0nXgBmHRfs0hzCw1lEmeMlOp6lnCx/nC/2RBCOrx1r+2z6ZrbZ3XCZHwT1TGQTXO6uOsBiTQnvfm+7maIsyHTqk0OFjVEDlfpGWt2r5rwhq+fXfjSUml5Li7odH5hoCWK8IVVB3ZJxnTOvGjEMcwwYCG/Z4SnFAQr3wK8n45Ulao11bZSyLsc8nLAbCsCzcpgAIozo2TFwuaAbm+D7gKaQBqfeH6PW905qiFbUxEB0CiupIkxkNK5gP9Go+8YIpS2cdB8NW8jd9oN7uArQ5+W2Z0VpIC0q4D7FuhogS8QwRMa3Ewo6KwJeSkX6uxInLnh/lTWwO93AGzL41lYGS8S5+UyxwlbA5n/8=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-backup-dictionaries-plugin

